# Generated by Django 5.2 on 2026-02-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_jobseeker_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(default=datetime.datetime(2026, 2, 17, 10, 50, 57, 148834, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
