# Generated by Django 5.2 on 2026-02-23 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_jobseeker_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(help_text='Sector', max_length=100)),
                ('established_at', models.DateField(null=True)),
                ('details', models.TextField(blank=True, help_text='Company description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('na', 'Prefer not to say')], max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='employer_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='mainapp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='mainapp.logininfo')),
            ],
        ),
    ]
